import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';

export default function Home() {

  const [offsetY, setOffsetY] = useState(0)
  const [offsetX, setOffsetX] = useState(0)
  const handleScroll = () => {
    setOffsetY(window.pageYOffset)
    // if (window.pageYOffset > 1000) {
    // setOffsetX(window.pageYOffset - 1000)
    
    // }
    setOffsetX(window.pageYOffset)
  }  

  useEffect(() => {
      window.addEventListener('scroll', handleScroll);

      return () => window.removeEventListener('scroll', handleScroll)
  }, [])
 
 
  // Dimension Iphone 6/7/8
 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main bg-amber-300 overflow-hidden '>
        {console.log(offsetY)}
        <section className='container bg-amber-300 h-screen' style={{transform: `translateY(-${offsetY * 0.2 }px)`}}>
          <div className='h-full  flex flex-col justify-center'>
            <h1 className="text-3xl font-bold underline text-center">Hello world!</h1>
         </div>
        </section>

        <section className='container bg-lime-300 h-screen translate-y-80 rotate-45  w-screen' >
          <div className='h-full  flex flex-col justify-center'>
          </div>
        </section>

        <section className='container bg-lime-300 h-screen' >
          <div className='h-full  flex flex-col  '>
            <div className='translate-x-3/4'>
              <h1 className="text-3xl font-bold underline text-center z-10" style={{transform: `translateX(-${offsetX * 0.3}px)`}}>Hi world!</h1>
            </div>
          </div>
        </section>

        <section className='container bg-cyan-300 h-screen overflow-auto ' style={{transform: `translateY(-${offsetY * 0.2 }px)`}}>
          <div className='h-full  flex flex-col justify-center' >
            <h1 className="text-3xl font-bold underline text-center">Good Bye !</h1>
         </div>
        </section>
      </main>
       
    </div>
  )
}
